name: Azure Deploy
on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**
  pull_request:
    branches:
      - main

workflow_dispatch: #Manual workflow trigger

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2.1.1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          

      - name: Set up Azure CLI
        uses: azure/CLI@v2
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{vars.RESOURCE_GROUP_NAME}} --location ${{vars.RESOURCE_GROUP_LOCATION}}
            echo "Azure resource group created successfully"

      - name: Deploy
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: ${{vars.RESOURCE_GROUP_NAME}}
          template: ./infrastructure/main.bicep