name: Go Service

on:
  push:
    branches: [ "main" ]
    paths:
      - "GoService/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "GoService/**"
  workflow_dispatch: # manual trigger

permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and export Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./GoService
          tags: go-app:latest
          outputs: type=docker,dest=/tmp/go-app.tar
      
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-app
          path: /tmp/go-app.tar
      
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: go-app
          path: /tmp
      
      - name: Load Docker image
        run: |
          docker load --input /tmp/go-app.tar
          docker image ls -a
      
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.GO_RESOURCE_NAME }}
          slot-name: 'Production'
          images: go-app:latest
